# Generated by Django 3.1.5 on 2021-01-26 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nccu_gis_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='imgDatas',
            new_name='imgData',
        ),
    ]
