# Generated by Django 3.1.5 on 2021-01-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nccu_gis_app', '0002_auto_20210126_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgdata',
            name='purl',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='imgdata',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='imgdata',
            name='lat',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='imgdata',
            name='lon',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='imgdata',
            name='title',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='imgdata',
            name='type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
