# Generated by Django 3.1.5 on 2021-02-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nccu_gis_app', '0003_auto_20210129_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgdata',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
