# Generated by Django 3.1.6 on 2021-04-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nccu_gis_app', '0004_imgdata_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='markerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=60)),
            ],
        ),
    ]
