# Generated by Django 3.1.6 on 2021-04-03 14:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nccu_gis_app', '0005_markertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgdata',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
