# Generated by Django 3.1.6 on 2021-04-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nccu_gis_app', '0006_auto_20210403_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgdata',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
