# Generated by Django 3.1.6 on 2021-04-03 14:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nccu_gis_app', '0007_auto_20210403_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgdata',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
